#!/bin/bash
i="file4.txt"
echo ""
echo "the main file is :"
echo ""
cat $i
echo ""
echo "----------Applying sed----------"
echo ""
echo "substitute :"
sed 's/001/1/' "$i"
echo ""
echo "Substitute 25 with 21 in complete file :"
sed 's/25/21/g' "$i"
echo ""
echo "Delete 2nd line :"
sed '2d' "$i"
echo ""
echo "delete last line : "
sed '$d' "$i"
echo ""
echo "Delete line from 1 to 4th line :"
sed '1,4d' "$i"
echo ""
echo "delete line from 5th line to end line :"
sed '4,$d' "$i"
echo ""
echo "delete line which contains 22 :"
sed '/22/d' "$i"
echo ""
echo "----------sed complete----------"
echo ""
